### ISSUE TITLE
AAMode eedi3 not working

### ISSUE THREAD

**Issue by RivenSkaye** [dubhater/vapoursynth-xaa#4]
`xaa.xaa(clip, mode="dr eedi3")` throws `vapoursynth.Error: EEDI3: Function does not take argument(s) named mclip`

**Comment by dubhater** [comment]
You need r4: https://github.com/HomeOfVapourSynthEvolution/VapourSynth-EEDI3/releases/tag/r4

**Comment by RivenSkaye** [comment]
Just re-downloaded it to make sure and I still get the same error:
```python
Failed to evaluate the script:
Python exception: EEDI3: Function does not take argument(s) named mclip

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 1946, in vapoursynth.vpy_evaluateScript
File "src\cython\vapoursynth.pyx", line 1947, in vapoursynth.vpy_evaluateScript
File "C:/Utilities/VapourSynth64Portable/Venus_Project_Climax-NCOP1.vpy", line 16, in 
xaa.xaa(denoise, mode="dr eedi3").set_output()
File "C:\Utilities\VapourSynth64Portable\Scripts\xaa.py", line 1100, in xaa
aaclip = xaa_dr(aaclip, aa_type, aa_pass, cplace, 48, nns, eediA, eediB, eediG, aa_sclip, aa_mcliph)
File "C:\Utilities\VapourSynth64Portable\Scripts\xaa.py", line 1658, in xaa_dr
aa = clip.eedi3m.EEDI3(field=3, alpha=alpha, beta=beta, gamma=gamma, sclip=sclip2, mclip=mclip)
File "src\cython\vapoursynth.pyx", line 1825, in vapoursynth.Function.__call__
vapoursynth.Error: EEDI3: Function does not take argument(s) named mclip```

**Comment by dubhater** [comment]
You must have an older copy of the plugin somewhere.

**Comment by dubhater** [comment]
Any progress?
